import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';
import type { DataSourceInfo, FoodQualityRecord, ParseResult } from '../types/quality';
import { parseQualityCsv } from '../utils/csvParser';
type ContextValue={records:FoodQualityRecord[];loading:boolean;loadError:string;importResult:ParseResult|null;source:DataSourceInfo|null;importCsv:(text:string,fileName?:string)=>void;resetSample:()=>void;retry:()=>void};
const QualityContext=createContext<ContextValue|null>(null);
const SESSION_KEY='food-qa-dashboard-session-v1';
export function QualityProvider({children}:{children:ReactNode}) { const [records,setRecords]=useState<FoodQualityRecord[]>([]);const[loading,setLoading]=useState(true);const[loadError,setLoadError]=useState('');const[importResult,setImportResult]=useState<ParseResult|null>(null);const[source,setSource]=useState<DataSourceInfo|null>(null);
  const load=()=>{setLoading(true);setLoadError('');fetch('/sample-food-quality-data.csv').then(r=>{if(!r.ok)throw new Error('Sample data could not be loaded');return r.text()}).then(t=>{const result=parseQualityCsv(t);setRecords(result.records);setSource({name:'Built-in sample dataset',importedAt:new Date().toISOString(),validRows:result.records.length,rejectedRows:result.errors.length,isSample:true});setImportResult(null);sessionStorage.removeItem(SESSION_KEY)}).catch(e=>setLoadError(e instanceof Error?e.message:'Unable to load data')).finally(()=>setLoading(false));};
  useEffect(()=>{try{const saved=sessionStorage.getItem(SESSION_KEY);if(saved){const value=JSON.parse(saved) as {records:FoodQualityRecord[];source:DataSourceInfo};setRecords(value.records);setSource(value.source);setLoading(false);return}}catch{sessionStorage.removeItem(SESSION_KEY)}load()},[]);
  const importCsv=(text:string,fileName='Uploaded CSV')=>{const result=parseQualityCsv(text);setImportResult(result);if(result.records.length){const nextSource={name:fileName,importedAt:new Date().toISOString(),validRows:result.records.length,rejectedRows:result.errors.length,isSample:false};setRecords(result.records);setSource(nextSource);setLoadError('');try{sessionStorage.setItem(SESSION_KEY,JSON.stringify({records:result.records,source:nextSource}))}catch{/* Large uploads still remain usable in memory. */}}};
  const value=useMemo(()=>({records,loading,loadError,importResult,source,importCsv,resetSample:load,retry:load}),[records,loading,loadError,importResult,source]);return <QualityContext.Provider value={value}>{children}</QualityContext.Provider> }
export function useQualityData(){const c=useContext(QualityContext);if(!c)throw new Error('useQualityData must be inside provider');return c}
