import { useMemo,useState } from 'react';import { Bar,BarChart,CartesianGrid,Cell,Legend,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';import type { FoodQualityRecord } from '../../types/quality';import { batchScores,failureReasons,productPerformance } from '../../utils/analytics';import { EmptyState } from '../ui/EmptyState';
const colors:Record<string,string>={PASS:'#059669',WARNING:'#d97706',FAIL:'#e11d48',INCOMPLETE:'#94a3b8'};
function Box({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <section className="card min-w-0 p-5"><h3 className="font-bold text-slate-900">{title}</h3><p className="mb-4 mt-1 text-xs text-slate-500">{subtitle}</p>{children}</section>}
const wrap=(node:React.ReactNode)=><div className="h-72 w-full">{node}</div>;
export function DashboardCharts({records}:{records:FoodQualityRecord[]}){const products=[...new Set(records.map(r=>r.product_name))];const[trendProduct,setTrendProduct]=useState('');const trend=useMemo(()=>records.filter(r=>!trendProduct||r.product_name===trendProduct).slice().sort((a,b)=>a.test_date.localeCompare(b.test_date)),[records,trendProduct]);const status=['PASS','WARNING','FAIL','INCOMPLETE'].map(name=>({name,value:records.filter(r=>r.status===name).length}));if(!records.length)return <EmptyState/>;return <div className="grid gap-5 xl:grid-cols-2">
  <Box title="Quality Status Overview" subtitle="Distribution of assessed sample outcomes">{wrap(<ResponsiveContainer><PieChart><Pie data={status} dataKey="value" nameKey="name" innerRadius={58} outerRadius={92} paddingAngle={3}>{status.map(x=><Cell key={x.name} fill={colors[x.name]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer>)}</Box>
  <Box title="Quality Score by Batch" subtitle="Average assessment score for each production batch">{wrap(<ResponsiveContainer><BarChart data={batchScores(records)} margin={{left:-15}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="batch" tick={{fontSize:11}}/><YAxis domain={[0,100]}/><Tooltip/><Bar dataKey="score" name="Average score" fill="#155483" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer>)}</Box>
  <Box title="pH Trend" subtitle="pH readings by test date"><select className="input mb-3 w-44" value={trendProduct} onChange={e=>setTrendProduct(e.target.value)}><option value="">All products</option>{products.map(x=><option key={x}>{x}</option>)}</select>{wrap(<ResponsiveContainer><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="test_date" tick={{fontSize:10}}/><YAxis domain={['auto','auto']}/><Tooltip/><Legend/><Line connectNulls={false} dataKey="ph" name="pH" stroke="#155483" strokeWidth={2} dot={{r:2}}/></LineChart></ResponsiveContainer>)}</Box>
  <Box title="Water Activity Trend" subtitle="Water activity readings over time">{wrap(<ResponsiveContainer><LineChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="test_date" tick={{fontSize:10}}/><YAxis domain={['auto','auto']}/><Tooltip/><Legend/><Line connectNulls={false} dataKey="water_activity" name="Water activity" stroke="#0891b2" strokeWidth={2} dot={{r:2}}/></LineChart></ResponsiveContainer>)}</Box>
  <Box title="Failure Reasons" subtitle="Count of failed readings by measured parameter">{wrap(<ResponsiveContainer><BarChart layout="vertical" data={failureReasons(records)} margin={{left:20}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis type="category" dataKey="name" width={92} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="count" name="Failures" fill="#e11d48" radius={[0,5,5,0]}/></BarChart></ResponsiveContainer>)}</Box>
  <Box title="Product Performance" subtitle="Pass rate and average quality score by product">{wrap(<ResponsiveContainer><BarChart data={productPerformance(records)}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="product" tick={{fontSize:10}}/><YAxis domain={[0,100]}/><Tooltip/><Legend/><Bar dataKey="passRate" name="Pass rate %" fill="#059669" radius={[4,4,0,0]}/><Bar dataKey="averageScore" name="Average score" fill="#155483" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>)}</Box>
  </div>}
